### ISSUE TITLE
V4 tailwindcss(native) rebuilding... all time.

### ISSUE THREAD

**Issue by pakerekchdz** [marklawlor/nativewind#583]
Clean expo router design with nativewind v4 added. Tested with versions ^4.0.0-alpha.20 and ^4.0.0-alpha.24. It just keeps building and never ending. I see:
`"tailwindcss(native) rebuilding... tailwindcss(native) is taking a long time to build, please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to speed up your build time"`

Why do you think this occurs? Does version ^4.0.0-alpha.20 and ^4.0.0-alpha.24 also cause tailwind to build applications indefinitely? Are these versions working? I would like to test it, thank you.

**Comment by dani-z** [comment]
@pakerekchdz in your `tailwind.config.js` make sure you replace 
`presets: [require("nativewind/preset").default],`
with 
`presets: [require("nativewind/preset")],`

**Comment by pakerekchdz** [comment]
I have presets: [require("nativewind/preset")]
I literally did it point by point from the information in the documentation.

**Comment by marklawlor** [comment]
Please share your repo. I cannot troubleshoot without a reproduction

**Comment by pakerekchdz** [comment]
https://drive.google.com/file/d/1COPWLx8StkT6lHgcT3FbCFI29ZxoPCDk/view?usp=sharing

I am providing an archive with files that contains only the minimum and the latest version of nativewind, which also does not work.

nativewind i expo router. Cały czas próbuje ładować

`tailwindcss(native) rebuilding... tailwindcss(native) is taking a long time to build, please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to speed up your build time`

What am I doing wrong? I run "npx expo start" normally

**Comment by marklawlor** [comment]
I cannot reproduce the issue with the example provided, which suggests this is an environmental issue.

What happens if you simply run Tailwind CLI on your project?

This is the command NativeWind runs to generate the styles.

`npx tailwindcss -i global.css -o node_modules/.cache/nativewind/global.css.native.css`

If this works fine for you (it finishs and generates the output file in `node_modules/.cache`, can you please add a `console.log(data)` to line `59` of `node_modules/nativewind/dist/metro/tailwind-cli.js` and reply with its output.

The error you are receiving comes from a timeout that is cleared only if a particular line of text is found "Done in" (which should be the last line from Tailwind CLI. Your Tailwind CLI is most likely failing or there is a edge case I haven't covered

**Comment by marklawlor** [comment]
Confirmed this is most likely the issue, most likely the path to your input file is invalid. I'll do a release that exposes better errors/warnings shortly

**Comment by pixelkoduje** [comment]
Did you detect it? Great. Please let me know in this thread when you patch so that others with this issue know. I'll be at the laptop tomorrow. If you are not successful by then, I will share the results with you.

PS. When do you plan to start working on space-*- and other child elements in version 4? Thank you for contributing to the development of a good RN.

**Comment by marklawlor** [comment]
I can replicate an issue that has the same symptoms of your issue, but I cannot reproduce your issue with the repo you provided. So I have no guarantee on a fix or any change. It's published now and hopefully it assists you, but I would still highly recommend following my previous troubleshooting steps.

`space-` is low on the priority list now that native `gap` is supported. What is your usecase where you require `space-` over `gap-`?

**Comment by pakerekchdz** [comment]
My folder is called "New projects" - it doesn't catch spaces?
Error: Specified input file D:\\New does not exist.

**Comment by pakerekchdz** [comment]
Next edit - The next problem - it does not respect the assigned classes at all. It assigns a className and nothing happens. The item has no styles.
![image](https://github.com/marklawlor/nativewind/assets/140351885/37d2e5d9-84b0-4a3b-95cb-e29f522e4bf4)

The best thing is that the styles are properly saved in the cache styles. global.css is imported in the layout.
![image](https://github.com/marklawlor/nativewind/assets/140351885/d83d794d-cabc-43cb-adf7-1729acb5fa49)

**Comment by tyrauber** [comment]
@marklawlor, the changes to `metro/tailwind-cli.ts` on main (d8420c1) resolve this issue in 4.0.0-alpha.27.

I noticed on main examples/expo-router (d8420c1) both `npx expo start --web` and  `npx expo start --web` hung.   I  debugged the issue in `dist/metro/tailwind-cli.js`, and went to commit my change to `metro/tailwind-cli.ts` when I discovered the file had been changed in the last 3 commits since 4.0.0-alpha.27 🤣. 

I ran build, and retested the both issues are now resolved. 🚀  Nice work.

**Comment by pixelkoduje** [comment]
Look at my previous message. Styles are not generated.

**Comment by pakerekchdz** [comment]
after add verifyInstalation

`Error: Nativewind: was unable to detect the 'nativewind/preset'. Please refer to http://nativewind.dev/troubleshooting#tailwind-preset`

my tailwind.config.js
`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {},
  },
  plugins: [],
}
`

**Comment by pakerekchdz** [comment]
Sorry, but I'm losing patience with this library. I wasted a few days on this. run it, and here is error after error and I can't even see the result.

**Comment by pakerekchdz** [comment]
Everything is connected correctly, but I still get the above error.

**Comment by marklawlor** [comment]
> Sorry, but I'm losing patience with this library. I wasted a few days on this. run it, and here is error after error and I can't even see the result.

@pakerekchdz You are using an unreleased alpha version. There will be bugs, that's why its unreleased.

Unfortunately I cannot fix those bugs if they are not correctly reported. Screenshots & zip files are never a good way to report an issue. Please commit your code to a github repo and share it.

> My folder is called "New projects" - it doesn't catch spaces?
Error: Specified input file D:\New does not exist.

Confirmed this is a bug that I'll now fix, thanks for the report.

>Next edit - The next problem - it does not respect the assigned classes at all. It assigns a className and nothing happens. The item has no styles. Version 4.0.0-alpha.29

It looks like you are using the components from the Expo Router starter. These components apply their own color/backgroundColor which will override the NativeWind styles. Use the normal Text/View from `react-native`

> And each of them has the same problem. When I reset the server, it literally adopted only one style. For example, text-xl, but when I changed it to xl2, none of them worked anymore.

Can you please provide an example of this in the repo? `text-xl2` is not a valid style.

**Comment by marklawlor** [comment]
Latest alpha should fix spaces with file directories

**Comment by marklawlor** [comment]
`4.0.0-alpha.31` has further fixes that should address these issues. I'm going to close this issue, but feel free to reply with new information and I'll reopen it again.

**Comment by Jemaz** [comment]
Just a heads up @marklawlor, as of version `4.0.16`, I'm getting the same issue still. 

The workaround is to make sure the absolute path to the project folder doesn't contain any white-spaces.

Easiest way to replicate the issue is to clone the `nativewind` project and just run the `/example` project but make sure the parent folder's name has some white space like "nativewind project".

**Comment by JN-forkwork** [comment]
Hey @tyrauber , I am using v4.0.18 and still hanging on `npx expo start --web`, can you help me debug?

**Comment by tyrauber** [comment]
@JN-forkwork, Try bumping to the latest release, [4.0.23](https://www.npmjs.com/package/nativewind/v/4.0.23).  Are you on SDK 50, with expo-router v3.4.6?

**Comment by JN-forkwork** [comment]
@tyrauber Thank you for the reply and hard work on this library. I was hasty to post this as I found the [issue ](https://github.com/marklawlor/nativewind/issues/610 ) already [resolved](https://github.com/marklawlor/nativewind/pull/743) but not yet merged. Hopefully 4.0.24 :)

**Comment by rmarquois** [comment]
> I cannot reproduce the issue with the example provided, which suggests this is an environmental issue.
> 
> What happens if you simply run Tailwind CLI on your project?
> 
> This is the command NativeWind runs to generate the styles.
> 
> `npx tailwindcss -i global.css -o node_modules/.cache/nativewind/global.css.native.css`
> 
> If this works fine for you (it finishs and generates the output file in `node_modules/.cache`, can you please add a `console.log(data)` to line `59` of `node_modules/nativewind/dist/metro/tailwind-cli.js` and reply with its output.
> 
> The error you are receiving comes from a timeout that is cleared only if a particular line of text is found "Done in" (which should be the last line from Tailwind CLI. Your Tailwind CLI is most likely failing or there is a edge case I haven't covered

Thanks a lot for your time and for this response. It was very helpful for me.

In my case it was because of a bad configuration in my Expo project and when rebuilding, it could not find postcss module. So as mentioned I put a console log in metro file and I got a Error: Cannot find module 'postcss' error.

I don't know if it's relevant but maybe you could log this kind of error to avoid the freeze.

**Comment by George-Acquah** [comment]
> I cannot reproduce the issue with the example provided, which suggests this is an environmental issue.
> 
> What happens if you simply run Tailwind CLI on your project?
> 
> This is the command NativeWind runs to generate the styles.
> 
> `npx tailwindcss -i global.css -o node_modules/.cache/nativewind/global.css.native.css`
> 
> If this works fine for you (it finishs and generates the output file in `node_modules/.cache`, can you please add a `console.log(data)` to line `59` of `node_modules/nativewind/dist/metro/tailwind-cli.js` and reply with its output.
> 
> The error you are receiving comes from a timeout that is cleared only if a particular line of text is found "Done in" (which should be the last line from Tailwind CLI. Your Tailwind CLI is most likely failing or there is a edge case I haven't covered

This is what was logged, but I found the fix from it. 
Thanks
throw err;
  ^

Error: Cannot find module 'D:\Personal\Dev\Mobile'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


Node.js v20.9.0

**Comment by rushi-mungse** [comment]
I am also struggling with this library. I losing my potential.  I like wasting my time with expo router! sorry but I am feel like that.

**Comment by rohankm** [comment]
facing the same problem

**Comment by VeniMitev** [comment]
@marklawlor same issue here. Build keeps on failing.

I can confirm that as of 4.0.23 that it errors out at paths such as "C:\1. Coding Projects". the console.log at `node_modules/nativewind/dist/metro/tailwind-cli.js` I get an error:

```
throw err;
^

Error: Cannot find module 'C:\1.'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by feledori** [comment]
check out #840

**Comment by adityabrahmankar** [comment]
> > I cannot reproduce the issue with the example provided, which suggests this is an environmental issue.
> > What happens if you simply run Tailwind CLI on your project?
> > This is the command NativeWind runs to generate the styles.
> > `npx tailwindcss -i global.css -o node_modules/.cache/nativewind/global.css.native.css`
> > If this works fine for you (it finishs and generates the output file in `node_modules/.cache`, can you please add a `console.log(data)` to line `59` of `node_modules/nativewind/dist/metro/tailwind-cli.js` and reply with its output.
> > The error you are receiving comes from a timeout that is cleared only if a particular line of text is found "Done in" (which should be the last line from Tailwind CLI. Your Tailwind CLI is most likely failing or there is a edge case I haven't covered
> 
> This is what was logged, but I found the fix from it. Thanks throw err; ^
> 
> Error: Cannot find module 'D:\Personal\Dev\Mobile' at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15) at Module._load (node:internal/modules/cjs/loader:901:27) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) at node:internal/main/run_main_module:23:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
> 
> Node.js v20.9.0

What was the fix?

**Comment by adityabrahmankar** [comment]
The fix is simple. If you have your app in a directory with black space name in my case it was "Mobile Development" renaming it to "Mobile" worked. 

So the temp fix until it is fixed from nativewind for which there's a pr 
#840 is to not have empty space in your project's root directory.

**Comment by 2-fly-4-ai** [comment]
This is still an issue. How can I suggest a PR fix for the  "nativewind": "^4.0.16", version being used in turborepot3. You need to escape your string properly; otherwise, windows throws CLI errors.

**Comment by feledori** [comment]
@2-fly-4-ai if you're using pnpm you can create a patch for it. [PNPM Patch](https://pnpm.io/cli/patch)

**Comment by 2-fly-4-ai** [comment]
> @2-fly-4-ai if you're using pnpm you can create a patch for it. [PNPM Patch](https://pnpm.io/cli/patch)

Do you know what's the difference between the version being used in t3turbo "nativewind": "^4.0.16", vs the latest version here which seems to be [nativewind@2.0.11](https://github.com/marklawlor/nativewind/releases/tag/nativewind%402.0.11).

They seem to be quite different.

**Comment by feledori** [comment]
4.0.36 is the latest version. It just not under the latest tag yet as the maintainer wants feedback and issue reports before going stable.

**Comment by P156HAM** [comment]
When using  verifyInstallation() from "nativewind";

ERROR  Error: Nativewind: was unable to detect the 'nativewind/preset'. Please refer to http://nativewind.dev/troubleshooting#tailwind-preset

the versions i am using: 
"tailwindcss": "^3.4.3",
"nativewind": "4.0.1",
"expo": "~50.0.17",
It feels like this error has been the same for the last many months, i see that someone reported the same error on october last year..

**Comment by franklinogf** [comment]
> When using verifyInstallation() from "nativewind";
> 
> ERROR Error: Nativewind: was unable to detect the 'nativewind/preset'. Please refer to http://nativewind.dev/troubleshooting#tailwind-preset
> 
> the versions i am using: "tailwindcss": "^3.4.3", "nativewind": "4.0.1", "expo": "~50.0.17", It feels like this error has been the same for the last many months, i see that someone reported the same error on october last year..

I'm having the same problem, the is nothing about this on the documentation

**Comment by tyrauber** [comment]
hey @franklinogf, that's the v2 documentation. You're looking for the 4.0.0 documentation [here](https://www.nativewind.dev/v4/getting-started/expo-router). Try bumping nativewind to the latest 4.0 release, currently [4.0.36](https://www.npmjs.com/package/nativewind/v/4.0.36), and make sure you configure expo correctly. Based on the error, I think [the babel config isn't correct](https://www.nativewind.dev/v4/getting-started/expo-router#3-add-the-babel-preset).

**Comment by sushofficial777** [comment]
> presets: [require("nativewind/preset")],

it worked in my case. thanks

**Comment by 2-fly-4-ai** [comment]
There still exists the issue where nativewinds cannot load properly when the user's name on their PC has a space in it (windows). It's in the tailwinds CLI part of the nativewinds node package. Seems like quite an oversight. I've run into this issue a couple of times and it's a bit of a pain to diagnose. Would highly recommend fixing this to avoid these pains to new devs trying it out.
